[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "bash deploy.sh"
healthcheckPath = "/api/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"