# Generated by Django 5.1.4 on 2025-10-24 07:09

from django.db import migrations, models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('paints', '0001_initial'),
    ]

    operations = [
        # Добавляем поле cost_price
        migrations.AddField(
            model_name='paint',
            name='cost_price',
            field=models.DecimalField(
                decimal_places=2, 
                default=Decimal('1.00'),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal('0.01'))],
                verbose_name='Себестоимость за единицу'
            ),
            preserve_default=False,
        ),
        
        # Переименовываем price_per_unit в selling_price
        migrations.RenameField(
            model_name='paint',
            old_name='price_per_unit',
            new_name='selling_price',
        ),
        
        # Изменяем verbose_name для selling_price
        migrations.AlterField(
            model_name='paint',
            name='selling_price',
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal('0.01'))],
                verbose_name='Цена продажи за единицу'
            ),
        ),
        
        # Создаем модель PriceHistory
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Предыдущая себестоимость')),
                ('new_cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Новая себестоимость')),
                ('old_selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Предыдущая цена продажи')),
                ('new_selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Новая цена продажи')),
                ('changed_by', models.CharField(blank=True, max_length=100, verbose_name='Изменено пользователем')),
                ('reason', models.TextField(blank=True, verbose_name='Причина изменения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paint', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='price_history', to='paints.paint', verbose_name='Краска')),
            ],
            options={
                'verbose_name': 'История изменения цен',
                'verbose_name_plural': 'История изменения цен',
                'ordering': ['-created_at'],
            },
        ),
    ]
