# Generated by Django 5.1.4 on 2025-10-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paints', '0003_set_default_cost_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='paint',
            name='product_type',
            field=models.CharField(choices=[('piece', 'Штучный товар'), ('measured', 'Метражный товар')], default='measured', max_length=10, verbose_name='Тип товара'),
        ),
    ]
