# Generated by Django 5.1.4 on 2025-10-24 07:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paints', '0004_paint_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя клиента')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Положительное значение - долг клиента, отрицательное - предоплата', max_digits=10, verbose_name='Баланс')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Оплачено'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Банковский перевод'), ('card', 'Оплата картой'), ('debt', 'В долг')], default='cash', max_length=10, verbose_name='Тип оплаты'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Заполняется автоматически при выборе клиента', max_length=200, verbose_name='Имя покупателя'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer_phone',
            field=models.CharField(blank=True, help_text='Заполняется автоматически при выборе клиента', max_length=20, verbose_name='Телефон покупателя'),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='paints.customer', verbose_name='Клиент'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма платежа')),
                ('payment_type', models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Банковский перевод'), ('card', 'Оплата картой')], default='cash', max_length=10, verbose_name='Тип оплаты')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата платежа')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_by', models.CharField(blank=True, max_length=100, verbose_name='Создано пользователем')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='paints.customer', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-payment_date'],
            },
        ),
    ]
