# Generated by Django 5.1.4 on 2025-10-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paints', '0005_customer_sale_paid_amount_sale_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paint',
            name='unit',
            field=models.CharField(choices=[('g', 'Граммы'), ('kg', 'Килограммы'), ('l', 'Литры'), ('ml', 'Миллилитры'), ('шт', 'Штуки'), ('упак', 'Упаковки'), ('комп', 'Комплекты'), ('м', 'Метры'), ('м²', 'Квадратные метры')], default='kg', max_length=5, verbose_name='Единица измерения'),
        ),
    ]
