# Generated by Django 5.1.4 on 2025-10-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paints', '0006_alter_paint_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paint',
            name='product_type',
            field=models.CharField(choices=[('piece', 'Штучный товар'), ('measured', 'Метражный товар'), ('volume', 'Объёмный товар')], default='measured', max_length=10, verbose_name='Тип товара'),
        ),
    ]
